<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AWSProjectType>Lambda</AWSProjectType>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.Core" Version="3.0.0" />
    <PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" Version="3.0.0" />
    <ProjectReference Include="../Hisaab.Api/Hisaab.Api.csproj" />
  </ItemGroup>
</Project>
