using Amazon.CDK;
using Amazon.CDK.AWS.Apigatewayv2;
using Amazon.CDK.AwsApigatewayv2Integrations;
using Amazon.CDK.AWS.CloudWatch;
using Amazon.CDK.AWS.DynamoDB;
using Amazon.CDK.AWS.Events;
using Amazon.CDK.AWS.Events.Targets;
using Amazon.CDK.AWS.IAM;
using Amazon.CDK.AWS.Lambda;
using Amazon.CDK.AWS.Lambda.EventSources;
using Amazon.CDK.AWS.Logs;
using Amazon.CDK.AWS.SQS;
using Amazon.CDK.AWS.S3;
using Constructs;
using Attribute = Amazon.CDK.AWS.DynamoDB.Attribute;
using Function = Amazon.CDK.AWS.Lambda.Function;
using LogGroupProps = Amazon.CDK.AWS.Logs.LogGroupProps;
using Queue = Amazon.CDK.AWS.SQS.Queue;

namespace Hisaab.Cdk;

public sealed class HisaabStack : Stack
{
    public HisaabStack(Construct scope, string id, string apiAssetPath, string workerAssetPath, IStackProps? props = null)
        : base(scope, id, props)
    {
        var configSecret = new CfnParameter(this, "ConfigurationSecretArn", new CfnParameterProps
        {
            Type = "String",
            Default = "",
            NoEcho = true,
            Description = "Existing Secrets Manager JSON configuration secret ARN; no credentials are generated by this stack.",
            AllowedPattern = "^$|^arn:[a-z-]+:secretsmanager:[a-z0-9-]+:[0-9]{12}:secret:.+$"
        });
        var hasConfigSecret = new CfnCondition(this, "HasConfigurationSecret", new CfnConditionProps
        {
            Expression = Fn.ConditionNot(Fn.ConditionEquals(configSecret.ValueAsString, ""))
        });
        var table = new Table(this, "Ledger", new TableProps
        {
            PartitionKey = new Attribute { Name = "PK", Type = AttributeType.STRING },
            SortKey = new Attribute { Name = "SK", Type = AttributeType.STRING },
            BillingMode = BillingMode.PAY_PER_REQUEST,
            Encryption = TableEncryption.AWS_MANAGED,
            PointInTimeRecoverySpecification = new PointInTimeRecoverySpecification { PointInTimeRecoveryEnabled = true },
            TimeToLiveAttribute = "ExpiresAt",
            Stream = StreamViewType.NEW_AND_OLD_IMAGES,
            DeletionProtection = true,
            RemovalPolicy = RemovalPolicy.RETAIN
        });
        var billingQueue = CreateQueue("Billing");
        var notificationQueue = CreateQueue("Notification");
        var receiptQueue = CreateQueue("Receipt");
        var receiptBucket = new Bucket(this, "ReceiptMedia", new BucketProps
        {
            Encryption = BucketEncryption.S3_MANAGED,
            BlockPublicAccess = BlockPublicAccess.BLOCK_ALL,
            EnforceSSL = true,
            ObjectOwnership = ObjectOwnership.BUCKET_OWNER_ENFORCED,
            Versioned = false,
            RemovalPolicy = RemovalPolicy.RETAIN,
            LifecycleRules = [new LifecycleRule { Id = "ExpireQuarantine", Prefix = "quarantine/", Expiration = Duration.Days(1), AbortIncompleteMultipartUploadAfter = Duration.Days(1) }]
        });
        var workerFailureQueue = new Queue(this, "WorkerFailureQueue", new QueueProps
        {
            Encryption = QueueEncryption.SQS_MANAGED,
            EnforceSSL = true,
            RetentionPeriod = Duration.Days(14)
        });
        new Alarm(this, "WorkerDeadLetters", new AlarmProps
        {
            Metric = workerFailureQueue.MetricApproximateNumberOfMessagesVisible(),
            Threshold = 1,
            EvaluationPeriods = 1,
            TreatMissingData = TreatMissingData.NOT_BREACHING
        });
        var environment = new Dictionary<string, string>
        {
            ["ASPNETCORE_ENVIRONMENT"] = "Production",
            ["Hisaab__DevAuth"] = "false",
            ["Hisaab__TableName"] = table.TableName,
            ["Hisaab__SecretsArn"] = configSecret.ValueAsString,
            ["Hisaab__BillingQueueUrl"] = billingQueue.QueueUrl,
            ["Hisaab__NotificationQueueUrl"] = notificationQueue.QueueUrl
            , ["Hisaab__Receipts__BucketName"] = receiptBucket.BucketName
            , ["Hisaab__Receipts__QueueUrl"] = receiptQueue.QueueUrl
        };
        var api = new Function(this, "Api", new FunctionProps
        {
            Runtime = Runtime.DOTNET_10,
            Architecture = Architecture.ARM_64,
            Handler = "Hisaab.Api",
            Code = Code.FromAsset(apiAssetPath),
            MemorySize = 1024,
            Timeout = Duration.Seconds(28),
            Environment = environment,
            LogGroup = new LogGroup(this, "ApiLogs", new LogGroupProps { Retention = RetentionDays.ONE_MONTH }),
            Tracing = Tracing.ACTIVE
        });
        var worker = new Function(this, "Worker", new FunctionProps
        {
            Runtime = Runtime.DOTNET_10,
            Architecture = Architecture.ARM_64,
            Handler = "Hisaab.Workers::Hisaab.Workers.Function::HandleAsync",
            Code = Code.FromAsset(workerAssetPath),
            MemorySize = 1024,
            Timeout = Duration.Seconds(60),
            Environment = environment,
            LogGroup = new LogGroup(this, "WorkerLogs", new LogGroupProps { Retention = RetentionDays.ONE_MONTH }),
            DeadLetterQueue = workerFailureQueue,
            RetryAttempts = 2,
            Tracing = Tracing.ACTIVE
        });
        var receiptLogs = new LogGroup(this, "ReceiptWorkerLogs", new LogGroupProps { Retention = RetentionDays.ONE_MONTH });
        var receiptWorker = new Function(this, "ReceiptWorker", new FunctionProps
        {
            Runtime = Runtime.DOTNET_10, Architecture = Architecture.ARM_64,
            Handler = "Hisaab.Workers::Hisaab.Workers.ReceiptFunction::HandleAsync",
            Code = Code.FromAsset(workerAssetPath), MemorySize = 1536, Timeout = Duration.Seconds(60),
            ReservedConcurrentExecutions = 4, Environment = environment, LogGroup = receiptLogs,
            LoggingFormat = LoggingFormat.TEXT,
            DeadLetterQueue = workerFailureQueue, RetryAttempts = 2, Tracing = Tracing.ACTIVE
        });
        receiptBucket.GrantPut(api, "quarantine/*");
        receiptBucket.GrantRead(api, "images/*");
        receiptBucket.GrantRead(api, "thumbs/*");
        receiptWorker.AddToRolePolicy(new PolicyStatement(new PolicyStatementProps
        {
            Actions = ["s3:GetObject", "s3:PutObject", "s3:DeleteObject", "s3:DeleteObjectVersion"],
            Resources = [receiptBucket.ArnForObjects("quarantine/*"), receiptBucket.ArnForObjects("images/*"), receiptBucket.ArnForObjects("thumbs/*")]
        }));
        receiptWorker.AddToRolePolicy(new PolicyStatement(new PolicyStatementProps
        {
            Actions = ["s3:ListBucketVersions"], Resources = [receiptBucket.BucketArn],
            Conditions = new Dictionary<string, object> { ["StringLike"] = new Dictionary<string, object> { ["s3:prefix"] = new[] { "quarantine/*", "images/*", "thumbs/*" } } }
        }));
        receiptQueue.GrantSendMessages(receiptWorker);
        receiptWorker.AddEventSource(new SqsEventSource(receiptQueue, new SqsEventSourceProps { BatchSize = 1, MaxConcurrency = 2 }));
        receiptWorker.AddEventSource(new DynamoEventSource(table, new DynamoEventSourceProps
        {
            StartingPosition = StartingPosition.TRIM_HORIZON, BatchSize = 20, RetryAttempts = 3, BisectBatchOnError = true,
            Filters = [FilterCriteria.Filter(new Dictionary<string, object>
            {
                ["eventName"] = new[] { "INSERT", "MODIFY" },
                ["dynamodb"] = new Dictionary<string, object> { ["Keys"] = new Dictionary<string, object> { ["PK"] = new Dictionary<string, object> { ["S"] = new[] { "WORK#receipt-scan" } } } }
            })], OnFailure = new SqsDlq(workerFailureQueue)
        }));
        ScheduleJob("ReceiptMaintenance", "receipt-maintenance", Duration.Minutes(1), receiptWorker, workerFailureQueue);
        new Alarm(this, "ReceiptWorkerErrors", new AlarmProps { Metric = receiptWorker.MetricErrors(), Threshold = 1, EvaluationPeriods = 1, TreatMissingData = TreatMissingData.NOT_BREACHING });
        new Alarm(this, "ReceiptQueueAge", new AlarmProps { Metric = receiptQueue.MetricApproximateAgeOfOldestMessage(), Threshold = 60, EvaluationPeriods = 1, TreatMissingData = TreatMissingData.NOT_BREACHING });
        foreach (var metricName in new[] { "Budget80", "CircuitOpen" })
            new Alarm(this, "Receipt" + metricName, new AlarmProps
            {
                Metric = new Metric(new MetricProps { Namespace = "Hisaab/Receipts", MetricName = metricName, Statistic = "Maximum", Period = Duration.Minutes(1) }),
                Threshold = 1, EvaluationPeriods = 1, TreatMissingData = TreatMissingData.NOT_BREACHING
            });
        foreach (var function in new[] { api, worker, receiptWorker })
        {
            function.AddToRolePolicy(new PolicyStatement(new PolicyStatementProps
            {
                Actions = ["dynamodb:GetItem", "dynamodb:Query", "dynamodb:PutItem", "dynamodb:DeleteItem", "dynamodb:ConditionCheckItem"],
                Resources = [table.TableArn]
            }));
        }
        var secretPolicy = new CfnPolicy(this, "ConfigurationSecretAccess", new CfnPolicyProps
        {
            PolicyName = "ReadHisaabConfiguration",
            Roles = [api.Role!.RoleName, worker.Role!.RoleName, receiptWorker.Role!.RoleName],
            PolicyDocument = new Dictionary<string, object>
            {
                ["Version"] = "2012-10-17",
                ["Statement"] = new object[]
                {
                    new Dictionary<string, object>
                    {
                        ["Effect"] = "Allow", ["Action"] = new[] { "secretsmanager:GetSecretValue" },
                        ["Resource"] = configSecret.ValueAsString
                    }
                }
            }
        });
        secretPolicy.CfnOptions.Condition = hasConfigSecret;
        billingQueue.GrantSendMessages(api);
        notificationQueue.GrantSendMessages(worker);
        worker.AddEventSource(new SqsEventSource(billingQueue, new SqsEventSourceProps { BatchSize = 10 }));
        worker.AddEventSource(new SqsEventSource(notificationQueue, new SqsEventSourceProps { BatchSize = 10 }));
        worker.AddEventSource(new DynamoEventSource(table, new DynamoEventSourceProps
        {
            StartingPosition = StartingPosition.TRIM_HORIZON,
            BatchSize = 100,
            RetryAttempts = 3,
            BisectBatchOnError = true,
            Filters = [FilterCriteria.Filter(new Dictionary<string, object>
            {
                ["eventName"] = new[] { "INSERT", "MODIFY" },
                ["dynamodb"] = new Dictionary<string, object>
                {
                    ["Keys"] = new Dictionary<string, object>
                    {
                        ["PK"] = new Dictionary<string, object> { ["S"] = new[] { "OUTBOX", "WORK#billing" } }
                    }
                }
            })],
            OnFailure = new SqsDlq(workerFailureQueue)
        }));
        ScheduleJob("OutboxDispatch", "outbox-dispatch", Duration.Minutes(1), worker, workerFailureQueue);
        ScheduleJob("BillingReconciliation", "billing-reconcile", Duration.Hours(1), worker, workerFailureQueue);
        ScheduleJob("AccountDeletion", "account-deletion", Duration.Hours(1), worker, workerFailureQueue);
        ScheduleJob("LedgerReconciliation", "ledger-reconcile", Duration.Days(1), worker, workerFailureQueue);

        var httpApi = new HttpApi(this, "HttpApi", new HttpApiProps
        {
            DefaultIntegration = new HttpLambdaIntegration("ApiIntegration", api),
            CreateDefaultStage = true
        });
        var stage = (CfnStage)httpApi.DefaultStage!.Node.DefaultChild!;
        stage.DefaultRouteSettings = new CfnStage.RouteSettingsProperty { ThrottlingBurstLimit = 100, ThrottlingRateLimit = 50 };
        var accessLogs = new LogGroup(this, "HttpAccessLogs", new LogGroupProps { Retention = RetentionDays.ONE_MONTH });
        stage.AccessLogSettings = new CfnStage.AccessLogSettingsProperty
        {
            DestinationArn = accessLogs.LogGroupArn,
            Format = "{\"requestId\":\"$context.requestId\",\"routeKey\":\"$context.routeKey\",\"status\":\"$context.status\",\"integrationLatency\":\"$context.integrationLatency\"}"
        };
        var apiMetricDimensions = new Dictionary<string, string> { ["ApiId"] = httpApi.ApiId, ["Stage"] = "$default" };
        var apiServerErrors = new Metric(new MetricProps
        {
            Namespace = "AWS/ApiGateway",
            MetricName = "5xx",
            DimensionsMap = apiMetricDimensions,
            Statistic = "Sum",
            Period = Duration.Minutes(5)
        });
        var apiRequestCount = new Metric(new MetricProps
        {
            Namespace = "AWS/ApiGateway",
            MetricName = "Count",
            DimensionsMap = apiMetricDimensions,
            Statistic = "Sum",
            Period = Duration.Minutes(5)
        });
        new Alarm(this, "HttpApiServerErrorRate", new AlarmProps
        {
            AlarmDescription = "HTTP API server errors reached 0.5% of requests in five minutes, including errors returned by application middleware.",
            Metric = new MathExpression(new MathExpressionProps
            {
                Expression = "IF(requests > 0, 100 * errors / requests, 0)",
                UsingMetrics = new Dictionary<string, IMetric> { ["errors"] = apiServerErrors, ["requests"] = apiRequestCount },
                Label = "HTTP API 5xx percentage",
                Period = Duration.Minutes(5)
            }),
            Threshold = 0.5,
            ComparisonOperator = ComparisonOperator.GREATER_THAN_OR_EQUAL_TO_THRESHOLD,
            EvaluationPeriods = 1,
            DatapointsToAlarm = 1,
            TreatMissingData = TreatMissingData.NOT_BREACHING
        });
        new Alarm(this, "ApiErrors", new AlarmProps
        {
            Metric = api.MetricErrors(),
            Threshold = 5,
            EvaluationPeriods = 1,
            TreatMissingData = TreatMissingData.NOT_BREACHING
        });
        new Alarm(this, "WorkerErrors", new AlarmProps
        {
            Metric = worker.MetricErrors(),
            Threshold = 1,
            EvaluationPeriods = 1,
            TreatMissingData = TreatMissingData.NOT_BREACHING
        });
        new CfnOutput(this, "ApiUrl", new CfnOutputProps { Value = httpApi.ApiEndpoint });
        new CfnOutput(this, "TableName", new CfnOutputProps { Value = table.TableName });
        new CfnOutput(this, "ReceiptBucketName", new CfnOutputProps { Value = receiptBucket.BucketName });
        new CfnOutput(this, "ReceiptWorkerRoleArn", new CfnOutputProps { Value = receiptWorker.Role!.RoleArn });
    }

    private Queue CreateQueue(string name)
    {
        var deadLetterQueue = new Queue(this, name + "DeadLetterQueue", new QueueProps
        {
            Encryption = QueueEncryption.SQS_MANAGED,
            EnforceSSL = true,
            RetentionPeriod = Duration.Days(14)
        });
        new Alarm(this, name + "DeadLetters", new AlarmProps
        {
            Metric = deadLetterQueue.MetricApproximateNumberOfMessagesVisible(),
            Threshold = 1,
            EvaluationPeriods = 3,
            TreatMissingData = TreatMissingData.NOT_BREACHING
        });
        return new Queue(this, name + "Queue", new QueueProps
        {
            Encryption = QueueEncryption.SQS_MANAGED,
            EnforceSSL = true,
            VisibilityTimeout = Duration.Minutes(6),
            RetentionPeriod = Duration.Days(4),
            DeadLetterQueue = new DeadLetterQueue { Queue = deadLetterQueue, MaxReceiveCount = 5 }
        });
    }

    private void ScheduleJob(string id, string job, Duration rate, Function worker, Queue failureQueue)
    {
        new Rule(this, id, new RuleProps
        {
            Schedule = Schedule.Rate(rate),
            Targets = [new LambdaFunction(worker, new LambdaFunctionProps
            {
                Event = RuleTargetInput.FromObject(new Dictionary<string, string> { ["job"] = job }),
                RetryAttempts = 2, DeadLetterQueue = failureQueue
            })]
        });
    }
}
